# docker-compose.yaml
version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-init:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Para desarrollo activo, descomenta esta línea para montar tu código dentro del contenedor
    # volumes:
    #   - ./:/app
